// <auto-generated />
using System;
using DCUExpoApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DCUExpoApp.Migrations
{
    [DbContext(typeof(ExpoContext))]
    [Migration("20240320200346_IndexProjectArea")]
    partial class IndexProjectArea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DCUExpoApp.Models.ExpoProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentProgrammeId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentProgrammeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ProjectArea", b =>
                {
                    b.Property<int>("ProjectAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectAreaId"));

                    b.Property<int?>("ExpoProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectAreaName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProjectAreaId");

                    b.HasIndex("ExpoProjectId");

                    b.HasIndex("ProjectAreaName");

                    b.ToTable("ProjectAreas");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ProjectStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExpoProjectId")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpoProjectId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ProjectTechnology", b =>
                {
                    b.Property<int>("ProjectTechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTechnologyId"));

                    b.Property<int?>("ExpoProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectTechnologyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectTechnologyId");

                    b.HasIndex("ExpoProjectId");

                    b.ToTable("ProjectTechnologies");
                });

            modelBuilder.Entity("DCUExpoApp.Models.StudentProgramme", b =>
                {
                    b.Property<int>("StudentProgrammeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentProgrammeId"));

                    b.Property<string>("StudentProgrammeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentProgrammeId");

                    b.ToTable("StudentProgrammes");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ExpoProject", b =>
                {
                    b.HasOne("DCUExpoApp.Models.StudentProgramme", "StudentProgramme")
                        .WithMany()
                        .HasForeignKey("StudentProgrammeId");

                    b.Navigation("StudentProgramme");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ProjectArea", b =>
                {
                    b.HasOne("DCUExpoApp.Models.ExpoProject", null)
                        .WithMany("ProjectAreas")
                        .HasForeignKey("ExpoProjectId");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ProjectStudent", b =>
                {
                    b.HasOne("DCUExpoApp.Models.ExpoProject", null)
                        .WithMany("ProjectStudents")
                        .HasForeignKey("ExpoProjectId");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ProjectTechnology", b =>
                {
                    b.HasOne("DCUExpoApp.Models.ExpoProject", null)
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("ExpoProjectId");
                });

            modelBuilder.Entity("DCUExpoApp.Models.ExpoProject", b =>
                {
                    b.Navigation("ProjectAreas");

                    b.Navigation("ProjectStudents");

                    b.Navigation("ProjectTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
