export var technologies = [
    ".NET",
    "3D slicer software",
    "Amplify",
    "Analog Electronics",
    "Android Studio",
    "Angular",
    "AngularJS",
    "ANSYS Fluent",
    "ANSYS Workbench",
    "API Gateway",
    "AppSync",
    "Arduino",
    "Arduino IDE",
    "AUD-D",
    "AUTOCAD",
    "AWS",
    "AWS Services",
    "Bash",
    "BERT",
    "Bioprocessing",
    "Blazor",
    "C#",
    "C/C++",
    "CloudFront",
    "Cognito",
    "Coqui AI",
    "CSS",
    "Dart",
    "DesignBuilder",
    "Digital Microscopy",
    "Digital Signal Processing",
    "Django",
    "Docker",
    "DynamoDB",
    "Eclipse",
    "Eel",
    "Elastic Search - Cosmos DB",
    "EnergyPlus",
    "Entity Component Systems",
    "Excel/VB",
    "Excel/VBA",
    "ExtendSIM",
    "Fast API",
    "Fast Fourier Transform",
    "Firebase",
    "Firebase & Firestore",
    "Flask",
    "FlaskAPI",
    "Flutter",
    "FPGA",
    "GaBi",
    "Ganache",
    "Ganry Echem Analysis Software",
    "G-Code",
    "Git",
    "Go",
    "Google Cloud Platform",
    "Google Maps API",
    "Google's MLKit",
    "GraphQL",
    "HOMER",
    "HTML",
    "HTML5",
    "Image J",
    "ImageJ",
    "Imaging",
    "InfluxDB",
    "Java",
    "JavaScript",
    "JQuery",
    "Judge0",
    "Keras",
    "KiCad",
    "Kickstart and Origin Pro",
    "Kotlin",
    "LabVIEW",
    "Lambda",
    "Laser Polishing",
    "Laser Technology",
    "Machine Learning",
    "MapBox",
    "Matlab",
    "microfluidics",
    "MLTU",
    "MongoDB",
    "Motoko",
    "MySQL",
    "NestJS",
    "NETZSCH DIL 402 PC",
    "NextJS",
    "Node.js",
    "Nodejs",
    "Nomad",
    "NoSQL",
    "Open SSL",
    "OpenCV",
    "OpenGL",
    "OpenModelica",
    "Oracle",
    "PaperSpace",
    "Peerjs",
    "Pillow",
    "PLC Programming",
    "Plotly",
    "Postgres",
    "PostgreSQL",
    "protobuf",
    "PSTrace",
    "PyTesseract",
    "Python",
    "R",
    "RASA",
    "React Native",
    "React.js",
    "React-Native",
    "Reinforcement Learning",
    "REST",
    "RStudio",
    "Rust",
    "S3",
    "Scilab",
    "SEM",
    "SEM and EDX",
    "SEM visual software",
    "Sendgrid",
    "Sensors",
    "Simulink",
    "Socket.io",
    "Solar Design Software",
    "Solidity",
    "Solidworks",
    "SPSS",
    "SQL",
    "SQLite",
    "Squid",
    "SSH into private GPU",
    "Starlark",
    "Surface Metrology and Analysis",
    "Svelte",
    "TailwindCSS",
    "Telegraf",
    "Tensorflow",
    "testXpert R",
    "Truffle",
    "TypeScript",
    "Unity Engine",
    "VHDL",
    "WebRTC",
    "Whisper",
    "XML"
];