export var areas = [
    "3D Bioprinting",
    "3D modelling",
    "3-D Modelling",
    "Additive Manufacturing",
    "Advanced Material Engineering",
    "Android",
    "Arduino",
    "Artificial Intelligence",
    "Audio Processing",
    "Augmented Reality",
    "Automation",
    "Automotive Technology",
    "Biomedical Engineering",
    "Biometrics",
    "Bioprocessing",
    "Blockchain technology",
    "Broadcast Software",
    "Carbon emissions",
    "CFD -- Drivetrain Testing",
    "Circuit Modeling",
    "Cloud Computing",
    "Computational Fluid Dynamics (CFD)",
    "Computer Architecture",
    "Computer Vision",
    "Container Orchestration",
    "Containerisation",
    "Content Management System",
    "Control Systems",
    "Cryptography",
    "Data Analytics",
    "Data Mining",
    "Databases",
    "Deep Learning",
    "Device Design",
    "Digital Signal Processing",
    "Distributed Systems",
    "E-Commerce",
    "Educational",
    "Electric Generation",
    "Embedded Systems",
    "Energy Conservation",
    "Energy Modelling",
    "Energy Storage Technology",
    "Environmental Mapping",
    "Environmental Sustainability",
    "Explainable AI",
    "Filesystems",
    "Finite Element Analysis",
    "Fintech",
    "Fluid Mechanics",
    "Food Waste Management",
    "Game Engines",
    "Gaming",
    "GPS--GIS",
    "Graphics",
    "Human-Computer Interaction",
    "Image--Video Processing",
    "Information Retrieval",
    "Instant Messaging",
    "Instrumentation",
    "Intell Transport System",
    "Intelligence Pattern Matching",
    "Internet of Things",
    "iOS app",
    "Lean Manufacturing",
    "Life Cycle Assessment",
    "Machine Learning",
    "Machine Translation",
    "Materials",
    "Materials Testing",
    "Mechanical Design and Manufacture",
    "Mechanical Engineering -- Cooling",
    "Mechanical Structural Analysis",
    "Mechatronic Systems",
    "Medical Manufacturing",
    "Medicine",
    "Meteorology",
    "Mobile App",
    "Model View Controller",
    "Motion Analysis",
    "Multimedia",
    "Natural Language Processing",
    "Network Applications",
    "Network Proxy",
    "Open Domain Question Answering",
    "Optical Character Recognition",
    "Optical Communications",
    "Pharmaceutical Technology",
    "Phenotyping",
    "Power Electronics",
    "Progressive Web Application",
    "PWA",
    "RaspberryPi",
    "Recommender System",
    "Recruitment Technology",
    "Rehabilitation Engineering",
    "Renewable Energy Technology",
    "Robotics",
    "Security",
    "Sensor Data",
    "Sensor Technology",
    "Sensor Technology Simulation",
    "Simulation",
    "Social Networking",
    "Software Development",
    "Speech Recognition",
    "Statistical Analysis",
    "Telecommunications",
    "Thermodynamics",
    "Time Series Forecasting",
    "Tissue Engineering",
    "Traffic Simulators",
    "Transport",
    "User Interface (UI) -- User Experience (UX) Design",
    "Vehicle Control",
    "Virtual Reality",
    "Water Treatment",
    "Wearable Technology",
    "Wearable_Technology",
    "Web Application",
    "Wireless Technology"
];
